import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./sidbar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ConvexClientProvider } from "@/app/convexClientProvider.tsx";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
                <ConvexClientProvider>
                    <TooltipProvider>
                        {children}
                    </TooltipProvider>
                </ConvexClientProvider>
            </body>
        </html>
    );
}

